name: InstaWP WordPress Testing

on:
  pull_request:
    types: [opened]

jobs:
  create-wp-for-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: instawp/wordpress-testing-automation@latest
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          INSTAWP_TOKEN: ${{secrets.INSTAWP_TOKEN}}
          EXPIRY_HOURS: 24 //optional
          INSTAWP_TEMPLATE_SLUG: gutenademonew //instawp template slug
          REPO_ID: 123 //instawp repo ID
          ARTIFACT_URL: https://yoursite.com/url.zip //optional
